version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
    -  POSTGRES_DB=${POSTGRES_DB}
    -  POSTGRES_USER=${POSTGRES_USER}
    -  POSTGRES_PASSWORD={POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  torvpn:
    build: ./torvpn
    container_name: torvpn
    restart: always
    ports:
      - "9050:9050"

  web:
    build: ./web
    container_name: web
    restart: always
    volumes:
      - ./web:/app

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/usr/share/nginx/html
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  cron:
    image: alpine
    container_name: certbot-cron
    volumes:
      - ./certbot:/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: >
      sh -c "echo '0 3 * * * certbot renew --webroot -w /var/www/certbot --quiet && nginx -s reload' | crontab - && crond -f"

volumes:
  pgdata: